homeassistant:


  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 116
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin



  customize:
    plant.dracaena_plant:
      friendly_name: Dracaena 
    plant.bedroom_plant:
      friendly_name: Bedroom Old 
    plant.yucca:
      friendly_name: Yucca 
    plant.bedroomnew_plant:
      friendly_name: Bedroom New 
    input_boolean.stuart_run:
      hidden: true
    input_boolean.in_bed:
      hidden: true
    group.all_automations:
      hidden: true
    sensor.miscale:
      hidden: true
    sensor.yucca_moisture:
      hidden: true
    sensor.yucca_battery:
      hidden: true
    sensor.yucca_temperature:
      hidden: true
    sensor.yucca_conductivity:
      hidden: true
    sensor.yucca_brightness:
      hidden: true
    sensor.dracaena_moisture:
      hidden: true
    sensor.dracaena_battery:
      hidden: true
    sensor.dracaena_temperature:
      hidden: true
    sensor.dracaena_conductivity:
      hidden: true
    sensor.dracaena_brightness:
      hidden: true
    sensor.bedroom_plant_moisture:
      hidden: true
    sensor.bedroom_plant_battery:
      hidden: true
    sensor.bedroom_plant_temperature:
      hidden: true
    sensor.bedroom_plant_conductivity:
      hidden: true
    sensor.bedroom_plant_brightness:
      hidden: true
    switch.frontdoor_light:
      hidden: true
    switch.garden_lights:
      hidden: true
    switch.conservatory_light:
      hidden: true

notify:
  - name: html5push
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id


shell_command:
  sleep_tom: 'curl -k http://tom-pc:8000/?action=System.Sleep'
  sleep_peter: 'curl -k http://192.168.178.86:8000/?action=System.Sleep'

alexa:

intent_script: !include alexa_intent_scripts.yaml

map:

# Enables the frontend
frontend:

# Enables configuration UI
config:

script: !include scripts.yaml

recorder:
  db_url: !secret db_url

influxdb:
  host: 192.168.178.20
  username: home-assistant
  password: !secret influxdb_password


http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
#discovery:

maxcube:
   host: 192.168.178.110

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google



google_assistant:
  project_id: !secret project_id
  client_id: !secret client_id
  access_token: !secret access_token
  exposed_domains:
    - switch
    - light
    - group

group: !include groups.yaml
automation: !include automations.yaml

emulated_hue:

input_boolean:
  alarmweekday:
    name: Weekdays only
    initial: on
    icon: mdi:calendar
  alarmweekon:
    name: Active
    initial: on

  stuart_run:
    name: Track whether Stuart has already run today
    initial: off
    icon: mdi:robot

  in_bed:
    name: In bed?
    initial: off
    icon: mdi:bed

  
xiaomi_aqara:
  gateways:
   - mac: 34:CE:00:83:80:EA
     key: !secret xiaomi_key

plant:
  yucca:
    sensors:
      moisture: sensor.yucca_moisture
      battery: sensor.yucca_battery
      temperature: sensor.yucca_temperature
      conductivity: sensor.yucca_conductivity
      brightness: sensor.yucca_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15
  bedroom_plant:
    sensors:
      moisture: sensor.bedroom_plant_moisture
      battery: sensor.bedroom_plant_battery
      temperature: sensor.bedroom_plant_temperature
      conductivity: sensor.bedroom_plant_conductivity
      brightness: sensor.bedroom_plant_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15
  dracaena_plant:
    sensors:
      moisture: sensor.dracaena_moisture
      battery: sensor.dracaena_battery
      temperature: sensor.dracaena_temperature
      conductivity: sensor.dracaena_conductivity
      brightness: sensor.dracaena_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15
  bedroomnew_plant:
    sensors:
      moisture: sensor.bedroomnew_moisture
      battery: sensor.bedroomnew_battery
      temperature: sensor.bedroomnew_temperature
      conductivity: sensor.bedroomnew_conductivity
      brightness: sensor.bedroomnew_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 500
    min_temperature: 15



switch:
  - platform: command_line
    switches:
      carport_camera:
        command_on: "/usr/bin/curl -X GET http://192.168.178.20:10090/http_switcher_on?module=HttpSwitcher.16"
        command_off: "/usr/bin/curl -X GET http://192.168.178.20:10090/http_switcher_off?module=HttpSwitcher.16"
        friendly_name: "Carport motion detector"
      frontdoor_camera:
        command_on: "/usr/bin/curl -X GET http://192.168.178.20:10090/http_switcher_on?module=HttpSwitcher.33"
        command_off: "/usr/bin/curl -X GET http://192.168.178.20:10090/http_switcher_off?module=HttpSwitcher.33"
        friendly_name: "Frontdoor motion detector"
      garden_camera:
        command_on: "/usr/bin/curl -X GET http://192.168.178.20:10090/http_switcher_on?module=HttpSwitcher.4"
        command_off: "/usr/bin/curl -X GET http://192.168.178.20:10090/http_switcher_off?module=HttpSwitcher.4"
        friendly_name: "Garden motion detector"
  - platform: sonoff
    switches:
      garden_lights:
        host: 192.168.178.103
        name: 'Garden Lights'
      conservatory_light:
        host: 192.168.178.112
        name: 'Conservatory Light'
      frontdoor_light:
        host: 192.168.178.120
        name: 'Frontdoor Light'
  - platform: broadlink
    host: 192.168.178.106
    mac: '34:EA:34:8E:E1:A4'
    timeout: 15
    switches:
      projector:
        friendly_name: "Projector Power"
        command_off: 'JgBIAAABH44QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQNBA0EBAQEBAQEDQQNBA0EBAQEBA0EBAQNBAQEBAQEBA0EDQQEBA0EAAFwQ0FAAAAAAAAAAAAAAAAAAA='
        command_on: 'JgBAAgABKZIUERQRFBEUEBQRFBEUERQRFBEUERMRFBEUNhQ1FBEUERQ2FDUUNhQ1FBEUERQ2FBETERQRFBEUERQ2EzYUERQ2FAAF'
  - platform: flux
    lights:
      - light.floalt_panel_ws_60x60 
      - light.floalt_panel_ws_60x60_2 
    name: Fluxer
    start_time: '7:00'
    stop_time: '23:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 2200
    brightness: 200
    disable_brightness_adjust: True
    mode: mired
  - platform: mqtt
    name: "Stuart"
    command_topic: "/home/neato/write"
    state_topic: "/home/neato/status"
    payload_on: "Clean House"
    payload_off: "Clean Stop"
#  - platform: mqtt
#    name: "Garden Lights"
#    state_topic: "/GardenLight/relay/Switch"
#    command_topic: "/GardenLight/gpio/12"
#    payload_on: "1"
#    payload_off: "0"
#    optimistic: true
#    qos: 0
#  - platform: mqtt
#    name: "Frontdoor Light"
#    state_topic: "/FrontDoor/relay/Switch"
#    command_topic: "/FrontDoor/gpio/12"
#    payload_on: "1"
#    payload_off: "0"
#    optimistic: true
#    qos: 0
  
  
sensor:
  - platform: mqtt
    name: "miscale"
    state_topic: "miscale/weight/kg"
    value_template: "{{ value }}"
    unit_of_measurement: "kg"
  - platform: mqtt
    name: "Boiler Output"
    state_topic: "/Boiler/out/Temperature"
    unit_of_measurement: "C"
  - platform: mqtt
    name: "Boiler Return"
    state_topic: "/Boiler/in/Temperature"
    unit_of_measurement: "C"

#  - platform: rest
#    resource: http://192.168.178.20:18003/location?group=narrownewt&user=tom
#    value_template: '{{ value_json.users.tom[0].location }}'
#    method: GET
#    name: Wheres Tom 
#    scan_interval: 1
  - platform: nut
    name: UPS
    host: 192.168.178.20
    port: 3493
    resources:
      - ups.load
      - ups.realpower.nominal
      - input.voltage
      - battery.runtime
  - platform: pi_hole
    host: 192.168.178.20
  - platform: template
    sensors:
      alarm_time:
        friendly_name: 'Time'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'

  
  - platform: google_travel_time
    api_key: !secret google_travel_time_api_key
    name: Time to work
    origin: device_tracker.toms_phone
    destination: !secret toms_work_address

  - platform: google_travel_time
    api_key: !secret google_travel_time_api_key
    name: Time to home
    origin: device_tracker.toms_phone
    destination: !secret home_address

  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: haveibeenpwned
    email:
      - tom@penberth.com
      - jane@penberth.com
      - dewgenenenny@gmail.com

  - platform: transmission
    host: !secret transmission_host
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'

  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage

  - platform: mqtt
    state_topic: "/ElectricCounter/kwh/Count"
    name: "Power usage"
    unit_of_measurement: "wH"

  - platform: mqtt
    state_topic: "/Dust Sensor/Dust/Dust"
    name: "Air Quality"
    unit_of_measurement: "mg/L"

  - platform: mqtt
    state_topic: "/home/neato/battery"
    name: "Stuarts Battery"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "outside_temp"
    name: "Outside Temperature"
    unit_of_measurement: "c"
    value_template: '{{ value_json.temp }}'

  - platform: mqtt
    state_topic: "outside_temp"
    name: "Outside Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity }}'

  - platform: mqtt
    state_topic: "outside_temp"
    name: "Atmospheric Pressure"
    unit_of_measurement: "mBars"
    value_template: '{{ value_json.pressure }}'

  - platform: mqtt
    state_topic: "kleikamp_brightness"
    name: "Outside Brightness"
    unit_of_measurement: "bright"
    value_template: '{{ value_json.Brightness }}'

  - platform: mqtt
    name: yucca_moisture
    state_topic: kleikamp12/plants/Yucca/
    value_template: '{{ value_json.moisture }}'
    hidden: true
  - platform: mqtt
    name: yucca_battery
    state_topic: kleikamp12/plants/Yucca/
    value_template: '{{ value_json.battery }}'
    hidden: true
  - platform: mqtt
    name: yucca_temperature
    state_topic: kleikamp12/plants/Yucca/
    value_template: '{{ value_json.temperature }}'
    hidden: true
  - platform: mqtt
    name: yucca_conductivity
    state_topic: kleikamp12/plants/Yucca/
    value_template: '{{ value_json.conductivity }}'
    hidden: true
  - platform: mqtt
    name: yucca_brightness
    state_topic: kleikamp12/plants/Yucca/
    value_template: '{{ value_json.brightness }}'
    hidden: true

  - platform: mqtt
    name: bedroomnew_moisture
    state_topic: kleikamp12/plants/BedroomNew/
    value_template: '{{ value_json.moisture }}'
    hidden: true
  - platform: mqtt
    name: bedroomnew_battery
    state_topic: kleikamp12/plants/BedroomNew/
    value_template: '{{ value_json.battery }}'
    hidden: true
  - platform: mqtt
    name: bedroomnew_temperature
    state_topic: kleikamp12/plants/BedroomNew/
    value_template: '{{ value_json.temperature }}'
    hidden: true
  - platform: mqtt
    name: bedroomnew_conductivity
    state_topic: kleikamp12/plants/BedroomNew/
    value_template: '{{ value_json.conductivity }}'
    hidden: true
  - platform: mqtt
    name: bedroomnew_brightness
    state_topic: kleikamp12/plants/BedroomNew/
    value_template: '{{ value_json.brightness }}'
    hidden: true

  - platform: mqtt
    name: dracaena_moisture
    state_topic: kleikamp12/plants/Dracaena/
    value_template: '{{ value_json.moisture }}'
    hidden: true
  - platform: mqtt
    name: dracaena_battery
    state_topic: kleikamp12/plants/Dracaena/
    value_template: '{{ value_json.battery }}'
    hidden: true
  - platform: mqtt
    name: dracaena_temperature
    state_topic: kleikamp12/plants/Dracaena/
    value_template: '{{ value_json.temperature }}'
    hidden: true
  - platform: mqtt
    name: dracaena_conductivity
    state_topic: kleikamp12/plants/Dracaena/
    value_template: '{{ value_json.conductivity }}'
    hidden: true
  - platform: mqtt
    name: dracaena_brightness
    state_topic: kleikamp12/plants/Dracaena/
    value_template: '{{ value_json.brightness }}'
    hidden: true

  - platform: mqtt
    name: bedroom_plant_moisture
    state_topic: kleikamp12/plants/bedroom_plant/
    value_template: '{{ value_json.moisture }}'
    hidden: true
  - platform: mqtt
    name: bedroom_plant_battery
    state_topic: kleikamp12/plants/bedroom_plant/
    value_template: '{{ value_json.battery }}'
    hidden: true
  - platform: mqtt
    name: bedroom_plant_temperature
    state_topic: kleikamp12/plants/bedroom_plant/
    value_template: '{{ value_json.temperature }}'
    hidden: true
  - platform: mqtt
    name: bedroom_plant_conductivity
    state_topic: kleikamp12/plants/bedroom_plant/
    value_template: '{{ value_json.conductivity }}'
    hidden: true
  - platform: mqtt
    name: bedroom_plant_brightness
    state_topic: kleikamp12/plants/bedroom_plant/
    value_template: '{{ value_json.brightness }}'
    hidden: true


  - platform: fritzbox_netmonitor
    host: 192.168.178.1
    monitored_conditions:
      - bytes_sent
      - bytes_received

  - platform: fritzbox_callmonitor
    host: 192.168.178.1
    username: !secret fritzbox_username
    password: !secret fritzbox_password

  - platform: openweathermap
    api_key: !secret owm_api_key
    forecast: 1
    monitored_conditions:
      - weather
      - temperature
      - humidity
      - pressure
      - clouds
      - rain
      - snow
      - wind_speed
      - wind_bearing

weather:
  - platform: openweathermap
    api_key: !secret owm_api_key

media_player:
  - platform: cast
    host: 192.168.178.21
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: kodi
    host: 192.168.178.234
    username: !secret kodi_username
    password: !secret kodi_password
  - platform: yamaha
    host: 192.168.178.32
    source_ignore:
     - "AV1"
     - "AV2"
     - "AV3"
     - "AV4"
     - "AV5"
     - "AV6"
     - "HDMI2"
     - "HDMI4"
     - "NET RADIO"
     - "AUDIO"
     - "SERVER"
     - "TUNER"
     - "USB"
     - "V-AUX"
     - "iPod (USB)"
     - "AirPlay"
    source_names:
      HDMI1: "Android TV"
      HDMI3: "PSTV"
      HDMI5: "ChromeCast"


device_tracker:
  - platform: gpslogger

zone:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 5000
  icon: mdi:factory

zone 2:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 500
  icon: mdi:home

zone 3:
  name: Braunschweig
  latitude: !secret braunschweig_latitude
  longitude: !secret braunschweig_longitude
  radius: 6000
  icon: mdi:city


camera:
 - platform: mjpeg
   mjpeg_url: !secret mjpeg_url
   name: Printer
 - platform: mjpeg
   mjpeg_url: http://192.168.178.20:10090/video7.mjpg?user=&fps=10
   still_image_url: http://192.168.178.20:10090/image7.jpg
   name: Garden
 - platform: mjpeg
   mjpeg_url: http://192.168.178.20:10090/video8.mjpg?user=&fps=10
   still_image_url: http://192.168.178.20:10090/image8.jpg
   name: Front_Door
 - platform: mjpeg
   mjpeg_url: http://192.168.178.20:10090/video13.mjpg?user=&fps=10
   still_image_url: http://192.168.178.20:10090/image13.jpg
   name: Car_Port
# - platform: xeoma
#   host: http://192.168.178.20:10090


# - platform: ffmpeg
#   name: Garden
#   input: rtsp://admin:@192.168.178.92:554/0/video0
  
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg



#image_processing:
#  - platform: dlib_face_detect
#    source:
#      - entity_id: camera.Printer

#image_processing:
#  - platform: opencv
#    name: Frontdoor_Faces
#    source:
#      - entity_id: camera.Front_Door
#    classifier:
#      mom: /config/haarcascade_fullbody.xml  

light:
  - platform: mqtt_json
    name: "Bedside Lamp"
    state_topic: "/home/bedside_lamp"
    command_topic: "/home/bedside_lamp/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: flux_led
    automatic_add: True
  - platform: template
    lights:
      garden_lights:
        friendly_name: "Garden Lights"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: switch.garden_lights
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: switch.garden_lights
      frontdoor_light:
        friendly_name: "Frontdoor Light"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: switch.frontdoor_light
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: switch.frontdoor_light
      conservatory_light:
        friendly_name: "Conservatory Light"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: switch.conservatory_light
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: switch.conservatory_light


mqtt:
  broker: 192.168.178.20

octoprint:
  host: 192.168.178.20:5000
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1



binary_sensor:
  - platform: trend
    sensors:
      haveibeenpwned:
        friendly_name: 'Tom pwned?' 
        entity_id: sensor.breaches_tom
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

proximity:
  home: 
    devices:
      - device_tracker.toms_phone
    tolerance: 50
    unit_of_measurement: km

tradfri:
  host: 192.168.178.83
#  api_key: GsNjIyPyi4lLL8n0


scene: !include scenes.yaml


input_number:
  alarmhour:
    name: Hour
    icon: mdi:timer
    initial: 5
    min: 0
    max: 23
    step: 1
  alarmminutes:
    name: Minutes
    icon: mdi:timer
    initial: 40
    min: 0
    max: 59
    step: 5

